### ISSUE TITLE
Lodash function specific anchors are not appearing on the search engines

### ISSUE THREAD

**Issue by AnandShiva** [lodash/lodash.com#255] opened 2022-04-16 00:10 UTC
When I type, lodash concat in google search, I would expect the direct link to https://lodash.com/docs/4.17.15#concat to come up. 
But I only see the main home page. This is mainly a search-related problem, but other docs don't behave like this (Eg try https://www.google.com/search?q=react+higher+order+components). I am open to contributing to this problem so that individual functions have their own entry point and are exposed as pages to search engines. Please let me know if is a issue seems a valid concern so that i can start making changes 🙂

**Comment by veksen** [comment] 2022-10-27 21:37
Sorry for slow turn around!

Very much a valid concern, this is very much a big item for us to solve!
Duplicate of #143 and in the process of solving this via a new website #201.

**Closed by veksen** 2022-10-27 21:37 UTC
Labels: duplicate
