### ISSUE TITLE
browser back/forward in the docs does not scroll to the anchor in the url

### ISSUE THREAD

**Issue by bughit** [lodash/lodash.com#106] opened 2016-11-14 19:48 UTC
Firefox 49, Chrome 54
an explicit navigation via urlbar does scroll, but back/forward does not

**Comment by jdalton** [comment] 2016-11-14 19:53
Hi @bughit!

This [recently landed](https://github.com/lodash/lodash.com/commit/e04893dc3f6e24ec8a565b41faba0ab1f01652ed). It looks like you may need to clear your cache.

**Closed by jdalton** 2016-11-14 19:53 UTC
Labels: invalid

**Comment by bughit** [comment] 2016-11-14 20:00
@jdalton I have an unproxied connection, I've force-reloaded, cleared the cache and even created a new profile, and both this and #107 are still present.

**Comment by jdalton** [comment] 2016-11-14 20:01
Hmm interesting. I can't repro the issue. It works for me with a fresh cache.

**Comment by bughit** [comment] 2016-11-14 20:13
This is what I getting for the response for https://lodash.com/docs/4.17.0:

Content-Length: 64375
Date: Mon, 14 Nov 2016 20:06:25 GMT
ETag: "f3bbee442f6a8b0edaf39487899b75eb-ssl-df"

Is this correct?

**Comment by bughit** [comment] 2016-11-14 20:19
@jdalton 
there's a 404 for:
https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js)

**Comment by jdalton** [comment] 2016-11-14 20:27
I can't repro that. It exists for me. Maybe it's a cdn issue with our host.

**Comment by bughit** [comment] 2016-11-14 20:41
@jdalton

I am consistently getting a 404 for https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js)

You should be able to see it in your server log.

> Maybe it's a cdn issue with our host.

Probably, but why does that make it not an issue (closed/invalid)?

Loading directly from jsdelivr works: https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js)

**Comment by jdalton** [comment] 2016-11-14 20:46
> Probably, but why does that make it not an issue (closed/invalid)?

It's closed because I cannot reproduce the problem. Since I cannot reproduce the problem there is very little I can do to resolve the problem. I have raised the issue with our host to see if they are aware of anything on their end.

**Comment by jdalton** [comment] 2016-11-14 20:47
I'll post back with any news. Until then I consider this issue closed.

**Comment by jdalton** [comment] 2016-11-16 18:23
For folks still getting 404's, I've let [netlfiy](https://www.netlify.com/) know.

**Comment by jdalton** [comment] 2016-11-17 00:11
Until the CDN issue is resolved I've made the service worker simply replace vendor paths with their external counterparts 💪
